/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 2.0.4
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package com.syz.example.utils.logutils;

import android.util.Log;

public class LogUtils {

    private static boolean open = false;

    private static final String DEFAULT_TAG = "LogUtils";

    /** info 级别*/
    public static final String LOG_LEVEL_INFO ="info";
    /** error 级别*/
    public static final String LOG_LEVEL_ERROR = "error";
    /** warning 级别*/
    public static final String LOG_LEVEL_WARN = "warning";

    /** 日志级别*/
    private static String LOG_LEVEL = LOG_LEVEL_INFO;

    /**
     * 文件日志开关；
     * @param open true 开启日志，false 关闭日志
     * @param logLevel 日志级别
     */
    public static void openLog(boolean open,String logLevel){
        LogUtils.open = open;
        LogUtils.LOG_LEVEL = logLevel;
    }

    /**
     * 日志打印
     * @param tag
     * @param logMsg
     */
    public static void print(String tag, String logMsg) {
        if(open) {
            if (tag == null) {
                tag = DEFAULT_TAG;
            }
            if (tag.length() < 20) {
                for (int i = 0; i < 20 - tag.length(); i++) {
                    tag = tag + " ";
                }
            }

            long threadId = Thread.currentThread().getId();
            if (LOG_LEVEL.equals(LOG_LEVEL_INFO)){
                Log.i(tag, "\t" + "pid:" + threadId + "\t" + tag + "\t" + logMsg);
            } else if (LOG_LEVEL.equals(LOG_LEVEL_ERROR)){
                Log.e(tag, "\t" + "pid:" + threadId + "\t" + tag + "\t" + logMsg);
            } else if (LOG_LEVEL.equals(LOG_LEVEL_WARN)){
                Log.w(tag, "\t" + "pid:" + threadId + "\t" + tag + "\t" + logMsg);
            }
            // 日志写文件
            LogService.getInstance().write("pid:" + threadId + "\t" + tag + "\t" + logMsg + "\n");
        }
    }
}
